// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify
// Copyright (c) Abstract Machines

// SPDX-License-Identifier: Apache-2.0

package mocks

import (
	"context"
	"time"

	"github.com/absmach/supermq/auth"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPATSRepository creates a new instance of MockPATSRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPATSRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPATSRepository {
	mock := &MockPATSRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPATSRepository is an autogenerated mock type for the PATSRepository type
type MockPATSRepository struct {
	mock.Mock
}

type MockPATSRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPATSRepository) EXPECT() *MockPATSRepository_Expecter {
	return &MockPATSRepository_Expecter{mock: &_m.Mock}
}

// AddScope provides a mock function for the type MockPATSRepository
func (_mock *MockPATSRepository) AddScope(ctx context.Context, userID string, scopes []auth.Scope) error {
	ret := _mock.Called(ctx, userID, scopes)

	if len(ret) == 0 {
		panic("no return value specified for AddScope")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []auth.Scope) error); ok {
		r0 = returnFunc(ctx, userID, scopes)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPATSRepository_AddScope_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddScope'
type MockPATSRepository_AddScope_Call struct {
	*mock.Call
}

// AddScope is a helper method to define mock.On call
//   - ctx
//   - userID
//   - scopes
func (_e *MockPATSRepository_Expecter) AddScope(ctx interface{}, userID interface{}, scopes interface{}) *MockPATSRepository_AddScope_Call {
	return &MockPATSRepository_AddScope_Call{Call: _e.mock.On("AddScope", ctx, userID, scopes)}
}

func (_c *MockPATSRepository_AddScope_Call) Run(run func(ctx context.Context, userID string, scopes []auth.Scope)) *MockPATSRepository_AddScope_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]auth.Scope))
	})
	return _c
}

func (_c *MockPATSRepository_AddScope_Call) Return(err error) *MockPATSRepository_AddScope_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPATSRepository_AddScope_Call) RunAndReturn(run func(ctx context.Context, userID string, scopes []auth.Scope) error) *MockPATSRepository_AddScope_Call {
	_c.Call.Return(run)
	return _c
}

// CheckScope provides a mock function for the type MockPATSRepository
func (_mock *MockPATSRepository) CheckScope(ctx context.Context, userID string, patID string, entityType auth.EntityType, optionalDomainID string, operation auth.Operation, entityID string) error {
	ret := _mock.Called(ctx, userID, patID, entityType, optionalDomainID, operation, entityID)

	if len(ret) == 0 {
		panic("no return value specified for CheckScope")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, auth.EntityType, string, auth.Operation, string) error); ok {
		r0 = returnFunc(ctx, userID, patID, entityType, optionalDomainID, operation, entityID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPATSRepository_CheckScope_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckScope'
type MockPATSRepository_CheckScope_Call struct {
	*mock.Call
}

// CheckScope is a helper method to define mock.On call
//   - ctx
//   - userID
//   - patID
//   - entityType
//   - optionalDomainID
//   - operation
//   - entityID
func (_e *MockPATSRepository_Expecter) CheckScope(ctx interface{}, userID interface{}, patID interface{}, entityType interface{}, optionalDomainID interface{}, operation interface{}, entityID interface{}) *MockPATSRepository_CheckScope_Call {
	return &MockPATSRepository_CheckScope_Call{Call: _e.mock.On("CheckScope", ctx, userID, patID, entityType, optionalDomainID, operation, entityID)}
}

func (_c *MockPATSRepository_CheckScope_Call) Run(run func(ctx context.Context, userID string, patID string, entityType auth.EntityType, optionalDomainID string, operation auth.Operation, entityID string)) *MockPATSRepository_CheckScope_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(auth.EntityType), args[4].(string), args[5].(auth.Operation), args[6].(string))
	})
	return _c
}

func (_c *MockPATSRepository_CheckScope_Call) Return(err error) *MockPATSRepository_CheckScope_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPATSRepository_CheckScope_Call) RunAndReturn(run func(ctx context.Context, userID string, patID string, entityType auth.EntityType, optionalDomainID string, operation auth.Operation, entityID string) error) *MockPATSRepository_CheckScope_Call {
	_c.Call.Return(run)
	return _c
}

// Reactivate provides a mock function for the type MockPATSRepository
func (_mock *MockPATSRepository) Reactivate(ctx context.Context, userID string, patID string) error {
	ret := _mock.Called(ctx, userID, patID)

	if len(ret) == 0 {
		panic("no return value specified for Reactivate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userID, patID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPATSRepository_Reactivate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reactivate'
type MockPATSRepository_Reactivate_Call struct {
	*mock.Call
}

// Reactivate is a helper method to define mock.On call
//   - ctx
//   - userID
//   - patID
func (_e *MockPATSRepository_Expecter) Reactivate(ctx interface{}, userID interface{}, patID interface{}) *MockPATSRepository_Reactivate_Call {
	return &MockPATSRepository_Reactivate_Call{Call: _e.mock.On("Reactivate", ctx, userID, patID)}
}

func (_c *MockPATSRepository_Reactivate_Call) Run(run func(ctx context.Context, userID string, patID string)) *MockPATSRepository_Reactivate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockPATSRepository_Reactivate_Call) Return(err error) *MockPATSRepository_Reactivate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPATSRepository_Reactivate_Call) RunAndReturn(run func(ctx context.Context, userID string, patID string) error) *MockPATSRepository_Reactivate_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type MockPATSRepository
func (_mock *MockPATSRepository) Remove(ctx context.Context, userID string, patID string) error {
	ret := _mock.Called(ctx, userID, patID)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userID, patID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPATSRepository_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockPATSRepository_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx
//   - userID
//   - patID
func (_e *MockPATSRepository_Expecter) Remove(ctx interface{}, userID interface{}, patID interface{}) *MockPATSRepository_Remove_Call {
	return &MockPATSRepository_Remove_Call{Call: _e.mock.On("Remove", ctx, userID, patID)}
}

func (_c *MockPATSRepository_Remove_Call) Run(run func(ctx context.Context, userID string, patID string)) *MockPATSRepository_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockPATSRepository_Remove_Call) Return(err error) *MockPATSRepository_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPATSRepository_Remove_Call) RunAndReturn(run func(ctx context.Context, userID string, patID string) error) *MockPATSRepository_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveAllPAT provides a mock function for the type MockPATSRepository
func (_mock *MockPATSRepository) RemoveAllPAT(ctx context.Context, userID string) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveAllPAT")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPATSRepository_RemoveAllPAT_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveAllPAT'
type MockPATSRepository_RemoveAllPAT_Call struct {
	*mock.Call
}

// RemoveAllPAT is a helper method to define mock.On call
//   - ctx
//   - userID
func (_e *MockPATSRepository_Expecter) RemoveAllPAT(ctx interface{}, userID interface{}) *MockPATSRepository_RemoveAllPAT_Call {
	return &MockPATSRepository_RemoveAllPAT_Call{Call: _e.mock.On("RemoveAllPAT", ctx, userID)}
}

func (_c *MockPATSRepository_RemoveAllPAT_Call) Run(run func(ctx context.Context, userID string)) *MockPATSRepository_RemoveAllPAT_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPATSRepository_RemoveAllPAT_Call) Return(err error) *MockPATSRepository_RemoveAllPAT_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPATSRepository_RemoveAllPAT_Call) RunAndReturn(run func(ctx context.Context, userID string) error) *MockPATSRepository_RemoveAllPAT_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveAllScope provides a mock function for the type MockPATSRepository
func (_mock *MockPATSRepository) RemoveAllScope(ctx context.Context, patID string) error {
	ret := _mock.Called(ctx, patID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveAllScope")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, patID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPATSRepository_RemoveAllScope_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveAllScope'
type MockPATSRepository_RemoveAllScope_Call struct {
	*mock.Call
}

// RemoveAllScope is a helper method to define mock.On call
//   - ctx
//   - patID
func (_e *MockPATSRepository_Expecter) RemoveAllScope(ctx interface{}, patID interface{}) *MockPATSRepository_RemoveAllScope_Call {
	return &MockPATSRepository_RemoveAllScope_Call{Call: _e.mock.On("RemoveAllScope", ctx, patID)}
}

func (_c *MockPATSRepository_RemoveAllScope_Call) Run(run func(ctx context.Context, patID string)) *MockPATSRepository_RemoveAllScope_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPATSRepository_RemoveAllScope_Call) Return(err error) *MockPATSRepository_RemoveAllScope_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPATSRepository_RemoveAllScope_Call) RunAndReturn(run func(ctx context.Context, patID string) error) *MockPATSRepository_RemoveAllScope_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveScope provides a mock function for the type MockPATSRepository
func (_mock *MockPATSRepository) RemoveScope(ctx context.Context, userID string, scopesIDs ...string) error {
	var tmpRet mock.Arguments
	if len(scopesIDs) > 0 {
		tmpRet = _mock.Called(ctx, userID, scopesIDs)
	} else {
		tmpRet = _mock.Called(ctx, userID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for RemoveScope")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...string) error); ok {
		r0 = returnFunc(ctx, userID, scopesIDs...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPATSRepository_RemoveScope_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveScope'
type MockPATSRepository_RemoveScope_Call struct {
	*mock.Call
}

// RemoveScope is a helper method to define mock.On call
//   - ctx
//   - userID
//   - scopesIDs
func (_e *MockPATSRepository_Expecter) RemoveScope(ctx interface{}, userID interface{}, scopesIDs ...interface{}) *MockPATSRepository_RemoveScope_Call {
	return &MockPATSRepository_RemoveScope_Call{Call: _e.mock.On("RemoveScope",
		append([]interface{}{ctx, userID}, scopesIDs...)...)}
}

func (_c *MockPATSRepository_RemoveScope_Call) Run(run func(ctx context.Context, userID string, scopesIDs ...string)) *MockPATSRepository_RemoveScope_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockPATSRepository_RemoveScope_Call) Return(err error) *MockPATSRepository_RemoveScope_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPATSRepository_RemoveScope_Call) RunAndReturn(run func(ctx context.Context, userID string, scopesIDs ...string) error) *MockPATSRepository_RemoveScope_Call {
	_c.Call.Return(run)
	return _c
}

// Retrieve provides a mock function for the type MockPATSRepository
func (_mock *MockPATSRepository) Retrieve(ctx context.Context, userID string, patID string) (auth.PAT, error) {
	ret := _mock.Called(ctx, userID, patID)

	if len(ret) == 0 {
		panic("no return value specified for Retrieve")
	}

	var r0 auth.PAT
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (auth.PAT, error)); ok {
		return returnFunc(ctx, userID, patID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) auth.PAT); ok {
		r0 = returnFunc(ctx, userID, patID)
	} else {
		r0 = ret.Get(0).(auth.PAT)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userID, patID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPATSRepository_Retrieve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Retrieve'
type MockPATSRepository_Retrieve_Call struct {
	*mock.Call
}

// Retrieve is a helper method to define mock.On call
//   - ctx
//   - userID
//   - patID
func (_e *MockPATSRepository_Expecter) Retrieve(ctx interface{}, userID interface{}, patID interface{}) *MockPATSRepository_Retrieve_Call {
	return &MockPATSRepository_Retrieve_Call{Call: _e.mock.On("Retrieve", ctx, userID, patID)}
}

func (_c *MockPATSRepository_Retrieve_Call) Run(run func(ctx context.Context, userID string, patID string)) *MockPATSRepository_Retrieve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockPATSRepository_Retrieve_Call) Return(pat auth.PAT, err error) *MockPATSRepository_Retrieve_Call {
	_c.Call.Return(pat, err)
	return _c
}

func (_c *MockPATSRepository_Retrieve_Call) RunAndReturn(run func(ctx context.Context, userID string, patID string) (auth.PAT, error)) *MockPATSRepository_Retrieve_Call {
	_c.Call.Return(run)
	return _c
}

// RetrieveAll provides a mock function for the type MockPATSRepository
func (_mock *MockPATSRepository) RetrieveAll(ctx context.Context, userID string, pm auth.PATSPageMeta) (auth.PATSPage, error) {
	ret := _mock.Called(ctx, userID, pm)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveAll")
	}

	var r0 auth.PATSPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, auth.PATSPageMeta) (auth.PATSPage, error)); ok {
		return returnFunc(ctx, userID, pm)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, auth.PATSPageMeta) auth.PATSPage); ok {
		r0 = returnFunc(ctx, userID, pm)
	} else {
		r0 = ret.Get(0).(auth.PATSPage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, auth.PATSPageMeta) error); ok {
		r1 = returnFunc(ctx, userID, pm)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPATSRepository_RetrieveAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveAll'
type MockPATSRepository_RetrieveAll_Call struct {
	*mock.Call
}

// RetrieveAll is a helper method to define mock.On call
//   - ctx
//   - userID
//   - pm
func (_e *MockPATSRepository_Expecter) RetrieveAll(ctx interface{}, userID interface{}, pm interface{}) *MockPATSRepository_RetrieveAll_Call {
	return &MockPATSRepository_RetrieveAll_Call{Call: _e.mock.On("RetrieveAll", ctx, userID, pm)}
}

func (_c *MockPATSRepository_RetrieveAll_Call) Run(run func(ctx context.Context, userID string, pm auth.PATSPageMeta)) *MockPATSRepository_RetrieveAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(auth.PATSPageMeta))
	})
	return _c
}

func (_c *MockPATSRepository_RetrieveAll_Call) Return(pats auth.PATSPage, err error) *MockPATSRepository_RetrieveAll_Call {
	_c.Call.Return(pats, err)
	return _c
}

func (_c *MockPATSRepository_RetrieveAll_Call) RunAndReturn(run func(ctx context.Context, userID string, pm auth.PATSPageMeta) (auth.PATSPage, error)) *MockPATSRepository_RetrieveAll_Call {
	_c.Call.Return(run)
	return _c
}

// RetrieveScope provides a mock function for the type MockPATSRepository
func (_mock *MockPATSRepository) RetrieveScope(ctx context.Context, pm auth.ScopesPageMeta) (auth.ScopesPage, error) {
	ret := _mock.Called(ctx, pm)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveScope")
	}

	var r0 auth.ScopesPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.ScopesPageMeta) (auth.ScopesPage, error)); ok {
		return returnFunc(ctx, pm)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.ScopesPageMeta) auth.ScopesPage); ok {
		r0 = returnFunc(ctx, pm)
	} else {
		r0 = ret.Get(0).(auth.ScopesPage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, auth.ScopesPageMeta) error); ok {
		r1 = returnFunc(ctx, pm)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPATSRepository_RetrieveScope_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveScope'
type MockPATSRepository_RetrieveScope_Call struct {
	*mock.Call
}

// RetrieveScope is a helper method to define mock.On call
//   - ctx
//   - pm
func (_e *MockPATSRepository_Expecter) RetrieveScope(ctx interface{}, pm interface{}) *MockPATSRepository_RetrieveScope_Call {
	return &MockPATSRepository_RetrieveScope_Call{Call: _e.mock.On("RetrieveScope", ctx, pm)}
}

func (_c *MockPATSRepository_RetrieveScope_Call) Run(run func(ctx context.Context, pm auth.ScopesPageMeta)) *MockPATSRepository_RetrieveScope_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(auth.ScopesPageMeta))
	})
	return _c
}

func (_c *MockPATSRepository_RetrieveScope_Call) Return(scopes auth.ScopesPage, err error) *MockPATSRepository_RetrieveScope_Call {
	_c.Call.Return(scopes, err)
	return _c
}

func (_c *MockPATSRepository_RetrieveScope_Call) RunAndReturn(run func(ctx context.Context, pm auth.ScopesPageMeta) (auth.ScopesPage, error)) *MockPATSRepository_RetrieveScope_Call {
	_c.Call.Return(run)
	return _c
}

// RetrieveSecretAndRevokeStatus provides a mock function for the type MockPATSRepository
func (_mock *MockPATSRepository) RetrieveSecretAndRevokeStatus(ctx context.Context, userID string, patID string) (string, bool, bool, error) {
	ret := _mock.Called(ctx, userID, patID)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveSecretAndRevokeStatus")
	}

	var r0 string
	var r1 bool
	var r2 bool
	var r3 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, bool, bool, error)); ok {
		return returnFunc(ctx, userID, patID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, userID, patID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) bool); ok {
		r1 = returnFunc(ctx, userID, patID)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) bool); ok {
		r2 = returnFunc(ctx, userID, patID)
	} else {
		r2 = ret.Get(2).(bool)
	}
	if returnFunc, ok := ret.Get(3).(func(context.Context, string, string) error); ok {
		r3 = returnFunc(ctx, userID, patID)
	} else {
		r3 = ret.Error(3)
	}
	return r0, r1, r2, r3
}

// MockPATSRepository_RetrieveSecretAndRevokeStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveSecretAndRevokeStatus'
type MockPATSRepository_RetrieveSecretAndRevokeStatus_Call struct {
	*mock.Call
}

// RetrieveSecretAndRevokeStatus is a helper method to define mock.On call
//   - ctx
//   - userID
//   - patID
func (_e *MockPATSRepository_Expecter) RetrieveSecretAndRevokeStatus(ctx interface{}, userID interface{}, patID interface{}) *MockPATSRepository_RetrieveSecretAndRevokeStatus_Call {
	return &MockPATSRepository_RetrieveSecretAndRevokeStatus_Call{Call: _e.mock.On("RetrieveSecretAndRevokeStatus", ctx, userID, patID)}
}

func (_c *MockPATSRepository_RetrieveSecretAndRevokeStatus_Call) Run(run func(ctx context.Context, userID string, patID string)) *MockPATSRepository_RetrieveSecretAndRevokeStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockPATSRepository_RetrieveSecretAndRevokeStatus_Call) Return(s string, b bool, b1 bool, err error) *MockPATSRepository_RetrieveSecretAndRevokeStatus_Call {
	_c.Call.Return(s, b, b1, err)
	return _c
}

func (_c *MockPATSRepository_RetrieveSecretAndRevokeStatus_Call) RunAndReturn(run func(ctx context.Context, userID string, patID string) (string, bool, bool, error)) *MockPATSRepository_RetrieveSecretAndRevokeStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function for the type MockPATSRepository
func (_mock *MockPATSRepository) Revoke(ctx context.Context, userID string, patID string) error {
	ret := _mock.Called(ctx, userID, patID)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userID, patID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPATSRepository_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type MockPATSRepository_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx
//   - userID
//   - patID
func (_e *MockPATSRepository_Expecter) Revoke(ctx interface{}, userID interface{}, patID interface{}) *MockPATSRepository_Revoke_Call {
	return &MockPATSRepository_Revoke_Call{Call: _e.mock.On("Revoke", ctx, userID, patID)}
}

func (_c *MockPATSRepository_Revoke_Call) Run(run func(ctx context.Context, userID string, patID string)) *MockPATSRepository_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockPATSRepository_Revoke_Call) Return(err error) *MockPATSRepository_Revoke_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPATSRepository_Revoke_Call) RunAndReturn(run func(ctx context.Context, userID string, patID string) error) *MockPATSRepository_Revoke_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockPATSRepository
func (_mock *MockPATSRepository) Save(ctx context.Context, pat auth.PAT) error {
	ret := _mock.Called(ctx, pat)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.PAT) error); ok {
		r0 = returnFunc(ctx, pat)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPATSRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockPATSRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx
//   - pat
func (_e *MockPATSRepository_Expecter) Save(ctx interface{}, pat interface{}) *MockPATSRepository_Save_Call {
	return &MockPATSRepository_Save_Call{Call: _e.mock.On("Save", ctx, pat)}
}

func (_c *MockPATSRepository_Save_Call) Run(run func(ctx context.Context, pat auth.PAT)) *MockPATSRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(auth.PAT))
	})
	return _c
}

func (_c *MockPATSRepository_Save_Call) Return(err error) *MockPATSRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPATSRepository_Save_Call) RunAndReturn(run func(ctx context.Context, pat auth.PAT) error) *MockPATSRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDescription provides a mock function for the type MockPATSRepository
func (_mock *MockPATSRepository) UpdateDescription(ctx context.Context, userID string, patID string, description string) (auth.PAT, error) {
	ret := _mock.Called(ctx, userID, patID, description)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDescription")
	}

	var r0 auth.PAT
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (auth.PAT, error)); ok {
		return returnFunc(ctx, userID, patID, description)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) auth.PAT); ok {
		r0 = returnFunc(ctx, userID, patID, description)
	} else {
		r0 = ret.Get(0).(auth.PAT)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, userID, patID, description)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPATSRepository_UpdateDescription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDescription'
type MockPATSRepository_UpdateDescription_Call struct {
	*mock.Call
}

// UpdateDescription is a helper method to define mock.On call
//   - ctx
//   - userID
//   - patID
//   - description
func (_e *MockPATSRepository_Expecter) UpdateDescription(ctx interface{}, userID interface{}, patID interface{}, description interface{}) *MockPATSRepository_UpdateDescription_Call {
	return &MockPATSRepository_UpdateDescription_Call{Call: _e.mock.On("UpdateDescription", ctx, userID, patID, description)}
}

func (_c *MockPATSRepository_UpdateDescription_Call) Run(run func(ctx context.Context, userID string, patID string, description string)) *MockPATSRepository_UpdateDescription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockPATSRepository_UpdateDescription_Call) Return(pAT auth.PAT, err error) *MockPATSRepository_UpdateDescription_Call {
	_c.Call.Return(pAT, err)
	return _c
}

func (_c *MockPATSRepository_UpdateDescription_Call) RunAndReturn(run func(ctx context.Context, userID string, patID string, description string) (auth.PAT, error)) *MockPATSRepository_UpdateDescription_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateName provides a mock function for the type MockPATSRepository
func (_mock *MockPATSRepository) UpdateName(ctx context.Context, userID string, patID string, name string) (auth.PAT, error) {
	ret := _mock.Called(ctx, userID, patID, name)

	if len(ret) == 0 {
		panic("no return value specified for UpdateName")
	}

	var r0 auth.PAT
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (auth.PAT, error)); ok {
		return returnFunc(ctx, userID, patID, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) auth.PAT); ok {
		r0 = returnFunc(ctx, userID, patID, name)
	} else {
		r0 = ret.Get(0).(auth.PAT)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, userID, patID, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPATSRepository_UpdateName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateName'
type MockPATSRepository_UpdateName_Call struct {
	*mock.Call
}

// UpdateName is a helper method to define mock.On call
//   - ctx
//   - userID
//   - patID
//   - name
func (_e *MockPATSRepository_Expecter) UpdateName(ctx interface{}, userID interface{}, patID interface{}, name interface{}) *MockPATSRepository_UpdateName_Call {
	return &MockPATSRepository_UpdateName_Call{Call: _e.mock.On("UpdateName", ctx, userID, patID, name)}
}

func (_c *MockPATSRepository_UpdateName_Call) Run(run func(ctx context.Context, userID string, patID string, name string)) *MockPATSRepository_UpdateName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockPATSRepository_UpdateName_Call) Return(pAT auth.PAT, err error) *MockPATSRepository_UpdateName_Call {
	_c.Call.Return(pAT, err)
	return _c
}

func (_c *MockPATSRepository_UpdateName_Call) RunAndReturn(run func(ctx context.Context, userID string, patID string, name string) (auth.PAT, error)) *MockPATSRepository_UpdateName_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTokenHash provides a mock function for the type MockPATSRepository
func (_mock *MockPATSRepository) UpdateTokenHash(ctx context.Context, userID string, patID string, tokenHash string, expiryAt time.Time) (auth.PAT, error) {
	ret := _mock.Called(ctx, userID, patID, tokenHash, expiryAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTokenHash")
	}

	var r0 auth.PAT
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, time.Time) (auth.PAT, error)); ok {
		return returnFunc(ctx, userID, patID, tokenHash, expiryAt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, time.Time) auth.PAT); ok {
		r0 = returnFunc(ctx, userID, patID, tokenHash, expiryAt)
	} else {
		r0 = ret.Get(0).(auth.PAT)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, time.Time) error); ok {
		r1 = returnFunc(ctx, userID, patID, tokenHash, expiryAt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPATSRepository_UpdateTokenHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTokenHash'
type MockPATSRepository_UpdateTokenHash_Call struct {
	*mock.Call
}

// UpdateTokenHash is a helper method to define mock.On call
//   - ctx
//   - userID
//   - patID
//   - tokenHash
//   - expiryAt
func (_e *MockPATSRepository_Expecter) UpdateTokenHash(ctx interface{}, userID interface{}, patID interface{}, tokenHash interface{}, expiryAt interface{}) *MockPATSRepository_UpdateTokenHash_Call {
	return &MockPATSRepository_UpdateTokenHash_Call{Call: _e.mock.On("UpdateTokenHash", ctx, userID, patID, tokenHash, expiryAt)}
}

func (_c *MockPATSRepository_UpdateTokenHash_Call) Run(run func(ctx context.Context, userID string, patID string, tokenHash string, expiryAt time.Time)) *MockPATSRepository_UpdateTokenHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(time.Time))
	})
	return _c
}

func (_c *MockPATSRepository_UpdateTokenHash_Call) Return(pAT auth.PAT, err error) *MockPATSRepository_UpdateTokenHash_Call {
	_c.Call.Return(pAT, err)
	return _c
}

func (_c *MockPATSRepository_UpdateTokenHash_Call) RunAndReturn(run func(ctx context.Context, userID string, patID string, tokenHash string, expiryAt time.Time) (auth.PAT, error)) *MockPATSRepository_UpdateTokenHash_Call {
	_c.Call.Return(run)
	return _c
}
