// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify
// Copyright (c) Abstract Machines

// SPDX-License-Identifier: Apache-2.0

package mocks

import (
	"context"
	"time"

	"github.com/absmach/supermq/auth"
	"github.com/absmach/supermq/pkg/policies"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// AddScope provides a mock function for the type MockService
func (_mock *MockService) AddScope(ctx context.Context, token string, patID string, scopes []auth.Scope) error {
	ret := _mock.Called(ctx, token, patID, scopes)

	if len(ret) == 0 {
		panic("no return value specified for AddScope")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []auth.Scope) error); ok {
		r0 = returnFunc(ctx, token, patID, scopes)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_AddScope_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddScope'
type MockService_AddScope_Call struct {
	*mock.Call
}

// AddScope is a helper method to define mock.On call
//   - ctx
//   - token
//   - patID
//   - scopes
func (_e *MockService_Expecter) AddScope(ctx interface{}, token interface{}, patID interface{}, scopes interface{}) *MockService_AddScope_Call {
	return &MockService_AddScope_Call{Call: _e.mock.On("AddScope", ctx, token, patID, scopes)}
}

func (_c *MockService_AddScope_Call) Run(run func(ctx context.Context, token string, patID string, scopes []auth.Scope)) *MockService_AddScope_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].([]auth.Scope))
	})
	return _c
}

func (_c *MockService_AddScope_Call) Return(err error) *MockService_AddScope_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_AddScope_Call) RunAndReturn(run func(ctx context.Context, token string, patID string, scopes []auth.Scope) error) *MockService_AddScope_Call {
	_c.Call.Return(run)
	return _c
}

// Authorize provides a mock function for the type MockService
func (_mock *MockService) Authorize(ctx context.Context, pr policies.Policy) error {
	ret := _mock.Called(ctx, pr)

	if len(ret) == 0 {
		panic("no return value specified for Authorize")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, policies.Policy) error); ok {
		r0 = returnFunc(ctx, pr)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Authorize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authorize'
type MockService_Authorize_Call struct {
	*mock.Call
}

// Authorize is a helper method to define mock.On call
//   - ctx
//   - pr
func (_e *MockService_Expecter) Authorize(ctx interface{}, pr interface{}) *MockService_Authorize_Call {
	return &MockService_Authorize_Call{Call: _e.mock.On("Authorize", ctx, pr)}
}

func (_c *MockService_Authorize_Call) Run(run func(ctx context.Context, pr policies.Policy)) *MockService_Authorize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(policies.Policy))
	})
	return _c
}

func (_c *MockService_Authorize_Call) Return(err error) *MockService_Authorize_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Authorize_Call) RunAndReturn(run func(ctx context.Context, pr policies.Policy) error) *MockService_Authorize_Call {
	_c.Call.Return(run)
	return _c
}

// AuthorizePAT provides a mock function for the type MockService
func (_mock *MockService) AuthorizePAT(ctx context.Context, userID string, patID string, entityType auth.EntityType, optionalDomainID string, operation auth.Operation, entityID string) error {
	ret := _mock.Called(ctx, userID, patID, entityType, optionalDomainID, operation, entityID)

	if len(ret) == 0 {
		panic("no return value specified for AuthorizePAT")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, auth.EntityType, string, auth.Operation, string) error); ok {
		r0 = returnFunc(ctx, userID, patID, entityType, optionalDomainID, operation, entityID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_AuthorizePAT_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthorizePAT'
type MockService_AuthorizePAT_Call struct {
	*mock.Call
}

// AuthorizePAT is a helper method to define mock.On call
//   - ctx
//   - userID
//   - patID
//   - entityType
//   - optionalDomainID
//   - operation
//   - entityID
func (_e *MockService_Expecter) AuthorizePAT(ctx interface{}, userID interface{}, patID interface{}, entityType interface{}, optionalDomainID interface{}, operation interface{}, entityID interface{}) *MockService_AuthorizePAT_Call {
	return &MockService_AuthorizePAT_Call{Call: _e.mock.On("AuthorizePAT", ctx, userID, patID, entityType, optionalDomainID, operation, entityID)}
}

func (_c *MockService_AuthorizePAT_Call) Run(run func(ctx context.Context, userID string, patID string, entityType auth.EntityType, optionalDomainID string, operation auth.Operation, entityID string)) *MockService_AuthorizePAT_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(auth.EntityType), args[4].(string), args[5].(auth.Operation), args[6].(string))
	})
	return _c
}

func (_c *MockService_AuthorizePAT_Call) Return(err error) *MockService_AuthorizePAT_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_AuthorizePAT_Call) RunAndReturn(run func(ctx context.Context, userID string, patID string, entityType auth.EntityType, optionalDomainID string, operation auth.Operation, entityID string) error) *MockService_AuthorizePAT_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePAT provides a mock function for the type MockService
func (_mock *MockService) CreatePAT(ctx context.Context, token string, name string, description string, duration time.Duration) (auth.PAT, error) {
	ret := _mock.Called(ctx, token, name, description, duration)

	if len(ret) == 0 {
		panic("no return value specified for CreatePAT")
	}

	var r0 auth.PAT
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, time.Duration) (auth.PAT, error)); ok {
		return returnFunc(ctx, token, name, description, duration)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, time.Duration) auth.PAT); ok {
		r0 = returnFunc(ctx, token, name, description, duration)
	} else {
		r0 = ret.Get(0).(auth.PAT)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, time.Duration) error); ok {
		r1 = returnFunc(ctx, token, name, description, duration)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_CreatePAT_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePAT'
type MockService_CreatePAT_Call struct {
	*mock.Call
}

// CreatePAT is a helper method to define mock.On call
//   - ctx
//   - token
//   - name
//   - description
//   - duration
func (_e *MockService_Expecter) CreatePAT(ctx interface{}, token interface{}, name interface{}, description interface{}, duration interface{}) *MockService_CreatePAT_Call {
	return &MockService_CreatePAT_Call{Call: _e.mock.On("CreatePAT", ctx, token, name, description, duration)}
}

func (_c *MockService_CreatePAT_Call) Run(run func(ctx context.Context, token string, name string, description string, duration time.Duration)) *MockService_CreatePAT_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(time.Duration))
	})
	return _c
}

func (_c *MockService_CreatePAT_Call) Return(pAT auth.PAT, err error) *MockService_CreatePAT_Call {
	_c.Call.Return(pAT, err)
	return _c
}

func (_c *MockService_CreatePAT_Call) RunAndReturn(run func(ctx context.Context, token string, name string, description string, duration time.Duration) (auth.PAT, error)) *MockService_CreatePAT_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePAT provides a mock function for the type MockService
func (_mock *MockService) DeletePAT(ctx context.Context, token string, patID string) error {
	ret := _mock.Called(ctx, token, patID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePAT")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, token, patID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeletePAT_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePAT'
type MockService_DeletePAT_Call struct {
	*mock.Call
}

// DeletePAT is a helper method to define mock.On call
//   - ctx
//   - token
//   - patID
func (_e *MockService_Expecter) DeletePAT(ctx interface{}, token interface{}, patID interface{}) *MockService_DeletePAT_Call {
	return &MockService_DeletePAT_Call{Call: _e.mock.On("DeletePAT", ctx, token, patID)}
}

func (_c *MockService_DeletePAT_Call) Run(run func(ctx context.Context, token string, patID string)) *MockService_DeletePAT_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_DeletePAT_Call) Return(err error) *MockService_DeletePAT_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeletePAT_Call) RunAndReturn(run func(ctx context.Context, token string, patID string) error) *MockService_DeletePAT_Call {
	_c.Call.Return(run)
	return _c
}

// Identify provides a mock function for the type MockService
func (_mock *MockService) Identify(ctx context.Context, token string) (auth.Key, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Identify")
	}

	var r0 auth.Key
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (auth.Key, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) auth.Key); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Get(0).(auth.Key)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Identify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Identify'
type MockService_Identify_Call struct {
	*mock.Call
}

// Identify is a helper method to define mock.On call
//   - ctx
//   - token
func (_e *MockService_Expecter) Identify(ctx interface{}, token interface{}) *MockService_Identify_Call {
	return &MockService_Identify_Call{Call: _e.mock.On("Identify", ctx, token)}
}

func (_c *MockService_Identify_Call) Run(run func(ctx context.Context, token string)) *MockService_Identify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_Identify_Call) Return(key auth.Key, err error) *MockService_Identify_Call {
	_c.Call.Return(key, err)
	return _c
}

func (_c *MockService_Identify_Call) RunAndReturn(run func(ctx context.Context, token string) (auth.Key, error)) *MockService_Identify_Call {
	_c.Call.Return(run)
	return _c
}

// IdentifyPAT provides a mock function for the type MockService
func (_mock *MockService) IdentifyPAT(ctx context.Context, paToken string) (auth.PAT, error) {
	ret := _mock.Called(ctx, paToken)

	if len(ret) == 0 {
		panic("no return value specified for IdentifyPAT")
	}

	var r0 auth.PAT
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (auth.PAT, error)); ok {
		return returnFunc(ctx, paToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) auth.PAT); ok {
		r0 = returnFunc(ctx, paToken)
	} else {
		r0 = ret.Get(0).(auth.PAT)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, paToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_IdentifyPAT_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IdentifyPAT'
type MockService_IdentifyPAT_Call struct {
	*mock.Call
}

// IdentifyPAT is a helper method to define mock.On call
//   - ctx
//   - paToken
func (_e *MockService_Expecter) IdentifyPAT(ctx interface{}, paToken interface{}) *MockService_IdentifyPAT_Call {
	return &MockService_IdentifyPAT_Call{Call: _e.mock.On("IdentifyPAT", ctx, paToken)}
}

func (_c *MockService_IdentifyPAT_Call) Run(run func(ctx context.Context, paToken string)) *MockService_IdentifyPAT_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_IdentifyPAT_Call) Return(pAT auth.PAT, err error) *MockService_IdentifyPAT_Call {
	_c.Call.Return(pAT, err)
	return _c
}

func (_c *MockService_IdentifyPAT_Call) RunAndReturn(run func(ctx context.Context, paToken string) (auth.PAT, error)) *MockService_IdentifyPAT_Call {
	_c.Call.Return(run)
	return _c
}

// Issue provides a mock function for the type MockService
func (_mock *MockService) Issue(ctx context.Context, token string, key auth.Key) (auth.Token, error) {
	ret := _mock.Called(ctx, token, key)

	if len(ret) == 0 {
		panic("no return value specified for Issue")
	}

	var r0 auth.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, auth.Key) (auth.Token, error)); ok {
		return returnFunc(ctx, token, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, auth.Key) auth.Token); ok {
		r0 = returnFunc(ctx, token, key)
	} else {
		r0 = ret.Get(0).(auth.Token)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, auth.Key) error); ok {
		r1 = returnFunc(ctx, token, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Issue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Issue'
type MockService_Issue_Call struct {
	*mock.Call
}

// Issue is a helper method to define mock.On call
//   - ctx
//   - token
//   - key
func (_e *MockService_Expecter) Issue(ctx interface{}, token interface{}, key interface{}) *MockService_Issue_Call {
	return &MockService_Issue_Call{Call: _e.mock.On("Issue", ctx, token, key)}
}

func (_c *MockService_Issue_Call) Run(run func(ctx context.Context, token string, key auth.Key)) *MockService_Issue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(auth.Key))
	})
	return _c
}

func (_c *MockService_Issue_Call) Return(token1 auth.Token, err error) *MockService_Issue_Call {
	_c.Call.Return(token1, err)
	return _c
}

func (_c *MockService_Issue_Call) RunAndReturn(run func(ctx context.Context, token string, key auth.Key) (auth.Token, error)) *MockService_Issue_Call {
	_c.Call.Return(run)
	return _c
}

// ListPATS provides a mock function for the type MockService
func (_mock *MockService) ListPATS(ctx context.Context, token string, pm auth.PATSPageMeta) (auth.PATSPage, error) {
	ret := _mock.Called(ctx, token, pm)

	if len(ret) == 0 {
		panic("no return value specified for ListPATS")
	}

	var r0 auth.PATSPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, auth.PATSPageMeta) (auth.PATSPage, error)); ok {
		return returnFunc(ctx, token, pm)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, auth.PATSPageMeta) auth.PATSPage); ok {
		r0 = returnFunc(ctx, token, pm)
	} else {
		r0 = ret.Get(0).(auth.PATSPage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, auth.PATSPageMeta) error); ok {
		r1 = returnFunc(ctx, token, pm)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListPATS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPATS'
type MockService_ListPATS_Call struct {
	*mock.Call
}

// ListPATS is a helper method to define mock.On call
//   - ctx
//   - token
//   - pm
func (_e *MockService_Expecter) ListPATS(ctx interface{}, token interface{}, pm interface{}) *MockService_ListPATS_Call {
	return &MockService_ListPATS_Call{Call: _e.mock.On("ListPATS", ctx, token, pm)}
}

func (_c *MockService_ListPATS_Call) Run(run func(ctx context.Context, token string, pm auth.PATSPageMeta)) *MockService_ListPATS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(auth.PATSPageMeta))
	})
	return _c
}

func (_c *MockService_ListPATS_Call) Return(pATSPage auth.PATSPage, err error) *MockService_ListPATS_Call {
	_c.Call.Return(pATSPage, err)
	return _c
}

func (_c *MockService_ListPATS_Call) RunAndReturn(run func(ctx context.Context, token string, pm auth.PATSPageMeta) (auth.PATSPage, error)) *MockService_ListPATS_Call {
	_c.Call.Return(run)
	return _c
}

// ListScopes provides a mock function for the type MockService
func (_mock *MockService) ListScopes(ctx context.Context, token string, pm auth.ScopesPageMeta) (auth.ScopesPage, error) {
	ret := _mock.Called(ctx, token, pm)

	if len(ret) == 0 {
		panic("no return value specified for ListScopes")
	}

	var r0 auth.ScopesPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, auth.ScopesPageMeta) (auth.ScopesPage, error)); ok {
		return returnFunc(ctx, token, pm)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, auth.ScopesPageMeta) auth.ScopesPage); ok {
		r0 = returnFunc(ctx, token, pm)
	} else {
		r0 = ret.Get(0).(auth.ScopesPage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, auth.ScopesPageMeta) error); ok {
		r1 = returnFunc(ctx, token, pm)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListScopes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListScopes'
type MockService_ListScopes_Call struct {
	*mock.Call
}

// ListScopes is a helper method to define mock.On call
//   - ctx
//   - token
//   - pm
func (_e *MockService_Expecter) ListScopes(ctx interface{}, token interface{}, pm interface{}) *MockService_ListScopes_Call {
	return &MockService_ListScopes_Call{Call: _e.mock.On("ListScopes", ctx, token, pm)}
}

func (_c *MockService_ListScopes_Call) Run(run func(ctx context.Context, token string, pm auth.ScopesPageMeta)) *MockService_ListScopes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(auth.ScopesPageMeta))
	})
	return _c
}

func (_c *MockService_ListScopes_Call) Return(scopesPage auth.ScopesPage, err error) *MockService_ListScopes_Call {
	_c.Call.Return(scopesPage, err)
	return _c
}

func (_c *MockService_ListScopes_Call) RunAndReturn(run func(ctx context.Context, token string, pm auth.ScopesPageMeta) (auth.ScopesPage, error)) *MockService_ListScopes_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveAllPAT provides a mock function for the type MockService
func (_mock *MockService) RemoveAllPAT(ctx context.Context, token string) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for RemoveAllPAT")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_RemoveAllPAT_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveAllPAT'
type MockService_RemoveAllPAT_Call struct {
	*mock.Call
}

// RemoveAllPAT is a helper method to define mock.On call
//   - ctx
//   - token
func (_e *MockService_Expecter) RemoveAllPAT(ctx interface{}, token interface{}) *MockService_RemoveAllPAT_Call {
	return &MockService_RemoveAllPAT_Call{Call: _e.mock.On("RemoveAllPAT", ctx, token)}
}

func (_c *MockService_RemoveAllPAT_Call) Run(run func(ctx context.Context, token string)) *MockService_RemoveAllPAT_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_RemoveAllPAT_Call) Return(err error) *MockService_RemoveAllPAT_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_RemoveAllPAT_Call) RunAndReturn(run func(ctx context.Context, token string) error) *MockService_RemoveAllPAT_Call {
	_c.Call.Return(run)
	return _c
}

// RemovePATAllScope provides a mock function for the type MockService
func (_mock *MockService) RemovePATAllScope(ctx context.Context, token string, patID string) error {
	ret := _mock.Called(ctx, token, patID)

	if len(ret) == 0 {
		panic("no return value specified for RemovePATAllScope")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, token, patID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_RemovePATAllScope_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemovePATAllScope'
type MockService_RemovePATAllScope_Call struct {
	*mock.Call
}

// RemovePATAllScope is a helper method to define mock.On call
//   - ctx
//   - token
//   - patID
func (_e *MockService_Expecter) RemovePATAllScope(ctx interface{}, token interface{}, patID interface{}) *MockService_RemovePATAllScope_Call {
	return &MockService_RemovePATAllScope_Call{Call: _e.mock.On("RemovePATAllScope", ctx, token, patID)}
}

func (_c *MockService_RemovePATAllScope_Call) Run(run func(ctx context.Context, token string, patID string)) *MockService_RemovePATAllScope_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_RemovePATAllScope_Call) Return(err error) *MockService_RemovePATAllScope_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_RemovePATAllScope_Call) RunAndReturn(run func(ctx context.Context, token string, patID string) error) *MockService_RemovePATAllScope_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveScope provides a mock function for the type MockService
func (_mock *MockService) RemoveScope(ctx context.Context, token string, patID string, scopeIDs ...string) error {
	var tmpRet mock.Arguments
	if len(scopeIDs) > 0 {
		tmpRet = _mock.Called(ctx, token, patID, scopeIDs)
	} else {
		tmpRet = _mock.Called(ctx, token, patID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for RemoveScope")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, ...string) error); ok {
		r0 = returnFunc(ctx, token, patID, scopeIDs...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_RemoveScope_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveScope'
type MockService_RemoveScope_Call struct {
	*mock.Call
}

// RemoveScope is a helper method to define mock.On call
//   - ctx
//   - token
//   - patID
//   - scopeIDs
func (_e *MockService_Expecter) RemoveScope(ctx interface{}, token interface{}, patID interface{}, scopeIDs ...interface{}) *MockService_RemoveScope_Call {
	return &MockService_RemoveScope_Call{Call: _e.mock.On("RemoveScope",
		append([]interface{}{ctx, token, patID}, scopeIDs...)...)}
}

func (_c *MockService_RemoveScope_Call) Run(run func(ctx context.Context, token string, patID string, scopeIDs ...string)) *MockService_RemoveScope_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockService_RemoveScope_Call) Return(err error) *MockService_RemoveScope_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_RemoveScope_Call) RunAndReturn(run func(ctx context.Context, token string, patID string, scopeIDs ...string) error) *MockService_RemoveScope_Call {
	_c.Call.Return(run)
	return _c
}

// ResetPATSecret provides a mock function for the type MockService
func (_mock *MockService) ResetPATSecret(ctx context.Context, token string, patID string, duration time.Duration) (auth.PAT, error) {
	ret := _mock.Called(ctx, token, patID, duration)

	if len(ret) == 0 {
		panic("no return value specified for ResetPATSecret")
	}

	var r0 auth.PAT
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) (auth.PAT, error)); ok {
		return returnFunc(ctx, token, patID, duration)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) auth.PAT); ok {
		r0 = returnFunc(ctx, token, patID, duration)
	} else {
		r0 = ret.Get(0).(auth.PAT)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, time.Duration) error); ok {
		r1 = returnFunc(ctx, token, patID, duration)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ResetPATSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetPATSecret'
type MockService_ResetPATSecret_Call struct {
	*mock.Call
}

// ResetPATSecret is a helper method to define mock.On call
//   - ctx
//   - token
//   - patID
//   - duration
func (_e *MockService_Expecter) ResetPATSecret(ctx interface{}, token interface{}, patID interface{}, duration interface{}) *MockService_ResetPATSecret_Call {
	return &MockService_ResetPATSecret_Call{Call: _e.mock.On("ResetPATSecret", ctx, token, patID, duration)}
}

func (_c *MockService_ResetPATSecret_Call) Run(run func(ctx context.Context, token string, patID string, duration time.Duration)) *MockService_ResetPATSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockService_ResetPATSecret_Call) Return(pAT auth.PAT, err error) *MockService_ResetPATSecret_Call {
	_c.Call.Return(pAT, err)
	return _c
}

func (_c *MockService_ResetPATSecret_Call) RunAndReturn(run func(ctx context.Context, token string, patID string, duration time.Duration) (auth.PAT, error)) *MockService_ResetPATSecret_Call {
	_c.Call.Return(run)
	return _c
}

// RetrieveKey provides a mock function for the type MockService
func (_mock *MockService) RetrieveKey(ctx context.Context, token string, id string) (auth.Key, error) {
	ret := _mock.Called(ctx, token, id)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveKey")
	}

	var r0 auth.Key
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (auth.Key, error)); ok {
		return returnFunc(ctx, token, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) auth.Key); ok {
		r0 = returnFunc(ctx, token, id)
	} else {
		r0 = ret.Get(0).(auth.Key)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, token, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_RetrieveKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveKey'
type MockService_RetrieveKey_Call struct {
	*mock.Call
}

// RetrieveKey is a helper method to define mock.On call
//   - ctx
//   - token
//   - id
func (_e *MockService_Expecter) RetrieveKey(ctx interface{}, token interface{}, id interface{}) *MockService_RetrieveKey_Call {
	return &MockService_RetrieveKey_Call{Call: _e.mock.On("RetrieveKey", ctx, token, id)}
}

func (_c *MockService_RetrieveKey_Call) Run(run func(ctx context.Context, token string, id string)) *MockService_RetrieveKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_RetrieveKey_Call) Return(key auth.Key, err error) *MockService_RetrieveKey_Call {
	_c.Call.Return(key, err)
	return _c
}

func (_c *MockService_RetrieveKey_Call) RunAndReturn(run func(ctx context.Context, token string, id string) (auth.Key, error)) *MockService_RetrieveKey_Call {
	_c.Call.Return(run)
	return _c
}

// RetrievePAT provides a mock function for the type MockService
func (_mock *MockService) RetrievePAT(ctx context.Context, userID string, patID string) (auth.PAT, error) {
	ret := _mock.Called(ctx, userID, patID)

	if len(ret) == 0 {
		panic("no return value specified for RetrievePAT")
	}

	var r0 auth.PAT
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (auth.PAT, error)); ok {
		return returnFunc(ctx, userID, patID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) auth.PAT); ok {
		r0 = returnFunc(ctx, userID, patID)
	} else {
		r0 = ret.Get(0).(auth.PAT)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userID, patID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_RetrievePAT_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrievePAT'
type MockService_RetrievePAT_Call struct {
	*mock.Call
}

// RetrievePAT is a helper method to define mock.On call
//   - ctx
//   - userID
//   - patID
func (_e *MockService_Expecter) RetrievePAT(ctx interface{}, userID interface{}, patID interface{}) *MockService_RetrievePAT_Call {
	return &MockService_RetrievePAT_Call{Call: _e.mock.On("RetrievePAT", ctx, userID, patID)}
}

func (_c *MockService_RetrievePAT_Call) Run(run func(ctx context.Context, userID string, patID string)) *MockService_RetrievePAT_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_RetrievePAT_Call) Return(pAT auth.PAT, err error) *MockService_RetrievePAT_Call {
	_c.Call.Return(pAT, err)
	return _c
}

func (_c *MockService_RetrievePAT_Call) RunAndReturn(run func(ctx context.Context, userID string, patID string) (auth.PAT, error)) *MockService_RetrievePAT_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function for the type MockService
func (_mock *MockService) Revoke(ctx context.Context, token string, id string) error {
	ret := _mock.Called(ctx, token, id)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, token, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type MockService_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx
//   - token
//   - id
func (_e *MockService_Expecter) Revoke(ctx interface{}, token interface{}, id interface{}) *MockService_Revoke_Call {
	return &MockService_Revoke_Call{Call: _e.mock.On("Revoke", ctx, token, id)}
}

func (_c *MockService_Revoke_Call) Run(run func(ctx context.Context, token string, id string)) *MockService_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_Revoke_Call) Return(err error) *MockService_Revoke_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Revoke_Call) RunAndReturn(run func(ctx context.Context, token string, id string) error) *MockService_Revoke_Call {
	_c.Call.Return(run)
	return _c
}

// RevokePATSecret provides a mock function for the type MockService
func (_mock *MockService) RevokePATSecret(ctx context.Context, token string, patID string) error {
	ret := _mock.Called(ctx, token, patID)

	if len(ret) == 0 {
		panic("no return value specified for RevokePATSecret")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, token, patID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_RevokePATSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokePATSecret'
type MockService_RevokePATSecret_Call struct {
	*mock.Call
}

// RevokePATSecret is a helper method to define mock.On call
//   - ctx
//   - token
//   - patID
func (_e *MockService_Expecter) RevokePATSecret(ctx interface{}, token interface{}, patID interface{}) *MockService_RevokePATSecret_Call {
	return &MockService_RevokePATSecret_Call{Call: _e.mock.On("RevokePATSecret", ctx, token, patID)}
}

func (_c *MockService_RevokePATSecret_Call) Run(run func(ctx context.Context, token string, patID string)) *MockService_RevokePATSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_RevokePATSecret_Call) Return(err error) *MockService_RevokePATSecret_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_RevokePATSecret_Call) RunAndReturn(run func(ctx context.Context, token string, patID string) error) *MockService_RevokePATSecret_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePATDescription provides a mock function for the type MockService
func (_mock *MockService) UpdatePATDescription(ctx context.Context, token string, patID string, description string) (auth.PAT, error) {
	ret := _mock.Called(ctx, token, patID, description)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePATDescription")
	}

	var r0 auth.PAT
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (auth.PAT, error)); ok {
		return returnFunc(ctx, token, patID, description)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) auth.PAT); ok {
		r0 = returnFunc(ctx, token, patID, description)
	} else {
		r0 = ret.Get(0).(auth.PAT)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, token, patID, description)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_UpdatePATDescription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePATDescription'
type MockService_UpdatePATDescription_Call struct {
	*mock.Call
}

// UpdatePATDescription is a helper method to define mock.On call
//   - ctx
//   - token
//   - patID
//   - description
func (_e *MockService_Expecter) UpdatePATDescription(ctx interface{}, token interface{}, patID interface{}, description interface{}) *MockService_UpdatePATDescription_Call {
	return &MockService_UpdatePATDescription_Call{Call: _e.mock.On("UpdatePATDescription", ctx, token, patID, description)}
}

func (_c *MockService_UpdatePATDescription_Call) Run(run func(ctx context.Context, token string, patID string, description string)) *MockService_UpdatePATDescription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockService_UpdatePATDescription_Call) Return(pAT auth.PAT, err error) *MockService_UpdatePATDescription_Call {
	_c.Call.Return(pAT, err)
	return _c
}

func (_c *MockService_UpdatePATDescription_Call) RunAndReturn(run func(ctx context.Context, token string, patID string, description string) (auth.PAT, error)) *MockService_UpdatePATDescription_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePATName provides a mock function for the type MockService
func (_mock *MockService) UpdatePATName(ctx context.Context, token string, patID string, name string) (auth.PAT, error) {
	ret := _mock.Called(ctx, token, patID, name)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePATName")
	}

	var r0 auth.PAT
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (auth.PAT, error)); ok {
		return returnFunc(ctx, token, patID, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) auth.PAT); ok {
		r0 = returnFunc(ctx, token, patID, name)
	} else {
		r0 = ret.Get(0).(auth.PAT)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, token, patID, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_UpdatePATName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePATName'
type MockService_UpdatePATName_Call struct {
	*mock.Call
}

// UpdatePATName is a helper method to define mock.On call
//   - ctx
//   - token
//   - patID
//   - name
func (_e *MockService_Expecter) UpdatePATName(ctx interface{}, token interface{}, patID interface{}, name interface{}) *MockService_UpdatePATName_Call {
	return &MockService_UpdatePATName_Call{Call: _e.mock.On("UpdatePATName", ctx, token, patID, name)}
}

func (_c *MockService_UpdatePATName_Call) Run(run func(ctx context.Context, token string, patID string, name string)) *MockService_UpdatePATName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockService_UpdatePATName_Call) Return(pAT auth.PAT, err error) *MockService_UpdatePATName_Call {
	_c.Call.Return(pAT, err)
	return _c
}

func (_c *MockService_UpdatePATName_Call) RunAndReturn(run func(ctx context.Context, token string, patID string, name string) (auth.PAT, error)) *MockService_UpdatePATName_Call {
	_c.Call.Return(run)
	return _c
}
