// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify
// Copyright (c) Abstract Machines

// SPDX-License-Identifier: Apache-2.0

package mocks

import (
	"context"

	"github.com/absmach/supermq/certs"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// IssueCert provides a mock function for the type MockService
func (_mock *MockService) IssueCert(ctx context.Context, domainID string, token string, clientID string, ttl string) (certs.Cert, error) {
	ret := _mock.Called(ctx, domainID, token, clientID, ttl)

	if len(ret) == 0 {
		panic("no return value specified for IssueCert")
	}

	var r0 certs.Cert
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) (certs.Cert, error)); ok {
		return returnFunc(ctx, domainID, token, clientID, ttl)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) certs.Cert); ok {
		r0 = returnFunc(ctx, domainID, token, clientID, ttl)
	} else {
		r0 = ret.Get(0).(certs.Cert)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = returnFunc(ctx, domainID, token, clientID, ttl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_IssueCert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IssueCert'
type MockService_IssueCert_Call struct {
	*mock.Call
}

// IssueCert is a helper method to define mock.On call
//   - ctx
//   - domainID
//   - token
//   - clientID
//   - ttl
func (_e *MockService_Expecter) IssueCert(ctx interface{}, domainID interface{}, token interface{}, clientID interface{}, ttl interface{}) *MockService_IssueCert_Call {
	return &MockService_IssueCert_Call{Call: _e.mock.On("IssueCert", ctx, domainID, token, clientID, ttl)}
}

func (_c *MockService_IssueCert_Call) Run(run func(ctx context.Context, domainID string, token string, clientID string, ttl string)) *MockService_IssueCert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockService_IssueCert_Call) Return(cert certs.Cert, err error) *MockService_IssueCert_Call {
	_c.Call.Return(cert, err)
	return _c
}

func (_c *MockService_IssueCert_Call) RunAndReturn(run func(ctx context.Context, domainID string, token string, clientID string, ttl string) (certs.Cert, error)) *MockService_IssueCert_Call {
	_c.Call.Return(run)
	return _c
}

// ListCerts provides a mock function for the type MockService
func (_mock *MockService) ListCerts(ctx context.Context, clientID string, pm certs.PageMetadata) (certs.CertPage, error) {
	ret := _mock.Called(ctx, clientID, pm)

	if len(ret) == 0 {
		panic("no return value specified for ListCerts")
	}

	var r0 certs.CertPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, certs.PageMetadata) (certs.CertPage, error)); ok {
		return returnFunc(ctx, clientID, pm)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, certs.PageMetadata) certs.CertPage); ok {
		r0 = returnFunc(ctx, clientID, pm)
	} else {
		r0 = ret.Get(0).(certs.CertPage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, certs.PageMetadata) error); ok {
		r1 = returnFunc(ctx, clientID, pm)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListCerts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCerts'
type MockService_ListCerts_Call struct {
	*mock.Call
}

// ListCerts is a helper method to define mock.On call
//   - ctx
//   - clientID
//   - pm
func (_e *MockService_Expecter) ListCerts(ctx interface{}, clientID interface{}, pm interface{}) *MockService_ListCerts_Call {
	return &MockService_ListCerts_Call{Call: _e.mock.On("ListCerts", ctx, clientID, pm)}
}

func (_c *MockService_ListCerts_Call) Run(run func(ctx context.Context, clientID string, pm certs.PageMetadata)) *MockService_ListCerts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(certs.PageMetadata))
	})
	return _c
}

func (_c *MockService_ListCerts_Call) Return(certPage certs.CertPage, err error) *MockService_ListCerts_Call {
	_c.Call.Return(certPage, err)
	return _c
}

func (_c *MockService_ListCerts_Call) RunAndReturn(run func(ctx context.Context, clientID string, pm certs.PageMetadata) (certs.CertPage, error)) *MockService_ListCerts_Call {
	_c.Call.Return(run)
	return _c
}

// ListSerials provides a mock function for the type MockService
func (_mock *MockService) ListSerials(ctx context.Context, clientID string, pm certs.PageMetadata) (certs.CertPage, error) {
	ret := _mock.Called(ctx, clientID, pm)

	if len(ret) == 0 {
		panic("no return value specified for ListSerials")
	}

	var r0 certs.CertPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, certs.PageMetadata) (certs.CertPage, error)); ok {
		return returnFunc(ctx, clientID, pm)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, certs.PageMetadata) certs.CertPage); ok {
		r0 = returnFunc(ctx, clientID, pm)
	} else {
		r0 = ret.Get(0).(certs.CertPage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, certs.PageMetadata) error); ok {
		r1 = returnFunc(ctx, clientID, pm)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListSerials_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSerials'
type MockService_ListSerials_Call struct {
	*mock.Call
}

// ListSerials is a helper method to define mock.On call
//   - ctx
//   - clientID
//   - pm
func (_e *MockService_Expecter) ListSerials(ctx interface{}, clientID interface{}, pm interface{}) *MockService_ListSerials_Call {
	return &MockService_ListSerials_Call{Call: _e.mock.On("ListSerials", ctx, clientID, pm)}
}

func (_c *MockService_ListSerials_Call) Run(run func(ctx context.Context, clientID string, pm certs.PageMetadata)) *MockService_ListSerials_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(certs.PageMetadata))
	})
	return _c
}

func (_c *MockService_ListSerials_Call) Return(certPage certs.CertPage, err error) *MockService_ListSerials_Call {
	_c.Call.Return(certPage, err)
	return _c
}

func (_c *MockService_ListSerials_Call) RunAndReturn(run func(ctx context.Context, clientID string, pm certs.PageMetadata) (certs.CertPage, error)) *MockService_ListSerials_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeCert provides a mock function for the type MockService
func (_mock *MockService) RevokeCert(ctx context.Context, domainID string, token string, clientID string) (certs.Revoke, error) {
	ret := _mock.Called(ctx, domainID, token, clientID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeCert")
	}

	var r0 certs.Revoke
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (certs.Revoke, error)); ok {
		return returnFunc(ctx, domainID, token, clientID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) certs.Revoke); ok {
		r0 = returnFunc(ctx, domainID, token, clientID)
	} else {
		r0 = ret.Get(0).(certs.Revoke)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, domainID, token, clientID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_RevokeCert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeCert'
type MockService_RevokeCert_Call struct {
	*mock.Call
}

// RevokeCert is a helper method to define mock.On call
//   - ctx
//   - domainID
//   - token
//   - clientID
func (_e *MockService_Expecter) RevokeCert(ctx interface{}, domainID interface{}, token interface{}, clientID interface{}) *MockService_RevokeCert_Call {
	return &MockService_RevokeCert_Call{Call: _e.mock.On("RevokeCert", ctx, domainID, token, clientID)}
}

func (_c *MockService_RevokeCert_Call) Run(run func(ctx context.Context, domainID string, token string, clientID string)) *MockService_RevokeCert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockService_RevokeCert_Call) Return(revoke certs.Revoke, err error) *MockService_RevokeCert_Call {
	_c.Call.Return(revoke, err)
	return _c
}

func (_c *MockService_RevokeCert_Call) RunAndReturn(run func(ctx context.Context, domainID string, token string, clientID string) (certs.Revoke, error)) *MockService_RevokeCert_Call {
	_c.Call.Return(run)
	return _c
}

// ViewCert provides a mock function for the type MockService
func (_mock *MockService) ViewCert(ctx context.Context, serialID string) (certs.Cert, error) {
	ret := _mock.Called(ctx, serialID)

	if len(ret) == 0 {
		panic("no return value specified for ViewCert")
	}

	var r0 certs.Cert
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (certs.Cert, error)); ok {
		return returnFunc(ctx, serialID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) certs.Cert); ok {
		r0 = returnFunc(ctx, serialID)
	} else {
		r0 = ret.Get(0).(certs.Cert)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, serialID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ViewCert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ViewCert'
type MockService_ViewCert_Call struct {
	*mock.Call
}

// ViewCert is a helper method to define mock.On call
//   - ctx
//   - serialID
func (_e *MockService_Expecter) ViewCert(ctx interface{}, serialID interface{}) *MockService_ViewCert_Call {
	return &MockService_ViewCert_Call{Call: _e.mock.On("ViewCert", ctx, serialID)}
}

func (_c *MockService_ViewCert_Call) Run(run func(ctx context.Context, serialID string)) *MockService_ViewCert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_ViewCert_Call) Return(cert certs.Cert, err error) *MockService_ViewCert_Call {
	_c.Call.Return(cert, err)
	return _c
}

func (_c *MockService_ViewCert_Call) RunAndReturn(run func(ctx context.Context, serialID string) (certs.Cert, error)) *MockService_ViewCert_Call {
	_c.Call.Return(run)
	return _c
}
