// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify
// Copyright (c) Abstract Machines

// SPDX-License-Identifier: Apache-2.0

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCallout creates a new instance of MockCallout. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCallout(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCallout {
	mock := &MockCallout{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCallout is an autogenerated mock type for the Callout type
type MockCallout struct {
	mock.Mock
}

type MockCallout_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCallout) EXPECT() *MockCallout_Expecter {
	return &MockCallout_Expecter{mock: &_m.Mock}
}

// Callout provides a mock function for the type MockCallout
func (_mock *MockCallout) Callout(ctx context.Context, perm string, pl map[string]interface{}) error {
	ret := _mock.Called(ctx, perm, pl)

	if len(ret) == 0 {
		panic("no return value specified for Callout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) error); ok {
		r0 = returnFunc(ctx, perm, pl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCallout_Callout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Callout'
type MockCallout_Callout_Call struct {
	*mock.Call
}

// Callout is a helper method to define mock.On call
//   - ctx
//   - perm
//   - pl
func (_e *MockCallout_Expecter) Callout(ctx interface{}, perm interface{}, pl interface{}) *MockCallout_Callout_Call {
	return &MockCallout_Callout_Call{Call: _e.mock.On("Callout", ctx, perm, pl)}
}

func (_c *MockCallout_Callout_Call) Run(run func(ctx context.Context, perm string, pl map[string]interface{})) *MockCallout_Callout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *MockCallout_Callout_Call) Return(err error) *MockCallout_Callout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCallout_Callout_Call) RunAndReturn(run func(ctx context.Context, perm string, pl map[string]interface{}) error) *MockCallout_Callout_Call {
	_c.Call.Return(run)
	return _c
}
