// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify
// Copyright (c) Abstract Machines

// SPDX-License-Identifier: Apache-2.0

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockEmailer creates a new instance of MockEmailer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmailer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmailer {
	mock := &MockEmailer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEmailer is an autogenerated mock type for the Emailer type
type MockEmailer struct {
	mock.Mock
}

type MockEmailer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmailer) EXPECT() *MockEmailer_Expecter {
	return &MockEmailer_Expecter{mock: &_m.Mock}
}

// SendPasswordReset provides a mock function for the type MockEmailer
func (_mock *MockEmailer) SendPasswordReset(To []string, host string, user string, token string) error {
	ret := _mock.Called(To, host, user, token)

	if len(ret) == 0 {
		panic("no return value specified for SendPasswordReset")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]string, string, string, string) error); ok {
		r0 = returnFunc(To, host, user, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEmailer_SendPasswordReset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendPasswordReset'
type MockEmailer_SendPasswordReset_Call struct {
	*mock.Call
}

// SendPasswordReset is a helper method to define mock.On call
//   - To
//   - host
//   - user
//   - token
func (_e *MockEmailer_Expecter) SendPasswordReset(To interface{}, host interface{}, user interface{}, token interface{}) *MockEmailer_SendPasswordReset_Call {
	return &MockEmailer_SendPasswordReset_Call{Call: _e.mock.On("SendPasswordReset", To, host, user, token)}
}

func (_c *MockEmailer_SendPasswordReset_Call) Run(run func(To []string, host string, user string, token string)) *MockEmailer_SendPasswordReset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockEmailer_SendPasswordReset_Call) Return(err error) *MockEmailer_SendPasswordReset_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEmailer_SendPasswordReset_Call) RunAndReturn(run func(To []string, host string, user string, token string) error) *MockEmailer_SendPasswordReset_Call {
	_c.Call.Return(run)
	return _c
}
