// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify
// Copyright (c) Abstract Machines

// SPDX-License-Identifier: Apache-2.0

package mocks

import (
	"github.com/absmach/supermq/readers"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMessageRepository creates a new instance of MockMessageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageRepository {
	mock := &MockMessageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMessageRepository is an autogenerated mock type for the MessageRepository type
type MockMessageRepository struct {
	mock.Mock
}

type MockMessageRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessageRepository) EXPECT() *MockMessageRepository_Expecter {
	return &MockMessageRepository_Expecter{mock: &_m.Mock}
}

// ReadAll provides a mock function for the type MockMessageRepository
func (_mock *MockMessageRepository) ReadAll(chanID string, pm readers.PageMetadata) (readers.MessagesPage, error) {
	ret := _mock.Called(chanID, pm)

	if len(ret) == 0 {
		panic("no return value specified for ReadAll")
	}

	var r0 readers.MessagesPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, readers.PageMetadata) (readers.MessagesPage, error)); ok {
		return returnFunc(chanID, pm)
	}
	if returnFunc, ok := ret.Get(0).(func(string, readers.PageMetadata) readers.MessagesPage); ok {
		r0 = returnFunc(chanID, pm)
	} else {
		r0 = ret.Get(0).(readers.MessagesPage)
	}
	if returnFunc, ok := ret.Get(1).(func(string, readers.PageMetadata) error); ok {
		r1 = returnFunc(chanID, pm)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMessageRepository_ReadAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadAll'
type MockMessageRepository_ReadAll_Call struct {
	*mock.Call
}

// ReadAll is a helper method to define mock.On call
//   - chanID
//   - pm
func (_e *MockMessageRepository_Expecter) ReadAll(chanID interface{}, pm interface{}) *MockMessageRepository_ReadAll_Call {
	return &MockMessageRepository_ReadAll_Call{Call: _e.mock.On("ReadAll", chanID, pm)}
}

func (_c *MockMessageRepository_ReadAll_Call) Run(run func(chanID string, pm readers.PageMetadata)) *MockMessageRepository_ReadAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(readers.PageMetadata))
	})
	return _c
}

func (_c *MockMessageRepository_ReadAll_Call) Return(messagesPage readers.MessagesPage, err error) *MockMessageRepository_ReadAll_Call {
	_c.Call.Return(messagesPage, err)
	return _c
}

func (_c *MockMessageRepository_ReadAll_Call) RunAndReturn(run func(chanID string, pm readers.PageMetadata) (readers.MessagesPage, error)) *MockMessageRepository_ReadAll_Call {
	_c.Call.Return(run)
	return _c
}
