// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify
// Copyright (c) Abstract Machines

// SPDX-License-Identifier: Apache-2.0

package mocks

import (
	"context"

	"github.com/absmach/supermq/journal"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// AddSubscription provides a mock function for the type MockRepository
func (_mock *MockRepository) AddSubscription(ctx context.Context, sub journal.ClientSubscription) error {
	ret := _mock.Called(ctx, sub)

	if len(ret) == 0 {
		panic("no return value specified for AddSubscription")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, journal.ClientSubscription) error); ok {
		r0 = returnFunc(ctx, sub)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_AddSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddSubscription'
type MockRepository_AddSubscription_Call struct {
	*mock.Call
}

// AddSubscription is a helper method to define mock.On call
//   - ctx
//   - sub
func (_e *MockRepository_Expecter) AddSubscription(ctx interface{}, sub interface{}) *MockRepository_AddSubscription_Call {
	return &MockRepository_AddSubscription_Call{Call: _e.mock.On("AddSubscription", ctx, sub)}
}

func (_c *MockRepository_AddSubscription_Call) Run(run func(ctx context.Context, sub journal.ClientSubscription)) *MockRepository_AddSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(journal.ClientSubscription))
	})
	return _c
}

func (_c *MockRepository_AddSubscription_Call) Return(err error) *MockRepository_AddSubscription_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_AddSubscription_Call) RunAndReturn(run func(ctx context.Context, sub journal.ClientSubscription) error) *MockRepository_AddSubscription_Call {
	_c.Call.Return(run)
	return _c
}

// CountSubscriptions provides a mock function for the type MockRepository
func (_mock *MockRepository) CountSubscriptions(ctx context.Context, clientID string) (uint64, error) {
	ret := _mock.Called(ctx, clientID)

	if len(ret) == 0 {
		panic("no return value specified for CountSubscriptions")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (uint64, error)); ok {
		return returnFunc(ctx, clientID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) uint64); ok {
		r0 = returnFunc(ctx, clientID)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, clientID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_CountSubscriptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountSubscriptions'
type MockRepository_CountSubscriptions_Call struct {
	*mock.Call
}

// CountSubscriptions is a helper method to define mock.On call
//   - ctx
//   - clientID
func (_e *MockRepository_Expecter) CountSubscriptions(ctx interface{}, clientID interface{}) *MockRepository_CountSubscriptions_Call {
	return &MockRepository_CountSubscriptions_Call{Call: _e.mock.On("CountSubscriptions", ctx, clientID)}
}

func (_c *MockRepository_CountSubscriptions_Call) Run(run func(ctx context.Context, clientID string)) *MockRepository_CountSubscriptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_CountSubscriptions_Call) Return(v uint64, err error) *MockRepository_CountSubscriptions_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockRepository_CountSubscriptions_Call) RunAndReturn(run func(ctx context.Context, clientID string) (uint64, error)) *MockRepository_CountSubscriptions_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteClientTelemetry provides a mock function for the type MockRepository
func (_mock *MockRepository) DeleteClientTelemetry(ctx context.Context, clientID string, domainID string) error {
	ret := _mock.Called(ctx, clientID, domainID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteClientTelemetry")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, clientID, domainID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_DeleteClientTelemetry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteClientTelemetry'
type MockRepository_DeleteClientTelemetry_Call struct {
	*mock.Call
}

// DeleteClientTelemetry is a helper method to define mock.On call
//   - ctx
//   - clientID
//   - domainID
func (_e *MockRepository_Expecter) DeleteClientTelemetry(ctx interface{}, clientID interface{}, domainID interface{}) *MockRepository_DeleteClientTelemetry_Call {
	return &MockRepository_DeleteClientTelemetry_Call{Call: _e.mock.On("DeleteClientTelemetry", ctx, clientID, domainID)}
}

func (_c *MockRepository_DeleteClientTelemetry_Call) Run(run func(ctx context.Context, clientID string, domainID string)) *MockRepository_DeleteClientTelemetry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRepository_DeleteClientTelemetry_Call) Return(err error) *MockRepository_DeleteClientTelemetry_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_DeleteClientTelemetry_Call) RunAndReturn(run func(ctx context.Context, clientID string, domainID string) error) *MockRepository_DeleteClientTelemetry_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementInboundMessages provides a mock function for the type MockRepository
func (_mock *MockRepository) IncrementInboundMessages(ctx context.Context, ct journal.ClientTelemetry) error {
	ret := _mock.Called(ctx, ct)

	if len(ret) == 0 {
		panic("no return value specified for IncrementInboundMessages")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, journal.ClientTelemetry) error); ok {
		r0 = returnFunc(ctx, ct)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_IncrementInboundMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementInboundMessages'
type MockRepository_IncrementInboundMessages_Call struct {
	*mock.Call
}

// IncrementInboundMessages is a helper method to define mock.On call
//   - ctx
//   - ct
func (_e *MockRepository_Expecter) IncrementInboundMessages(ctx interface{}, ct interface{}) *MockRepository_IncrementInboundMessages_Call {
	return &MockRepository_IncrementInboundMessages_Call{Call: _e.mock.On("IncrementInboundMessages", ctx, ct)}
}

func (_c *MockRepository_IncrementInboundMessages_Call) Run(run func(ctx context.Context, ct journal.ClientTelemetry)) *MockRepository_IncrementInboundMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(journal.ClientTelemetry))
	})
	return _c
}

func (_c *MockRepository_IncrementInboundMessages_Call) Return(err error) *MockRepository_IncrementInboundMessages_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_IncrementInboundMessages_Call) RunAndReturn(run func(ctx context.Context, ct journal.ClientTelemetry) error) *MockRepository_IncrementInboundMessages_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementOutboundMessages provides a mock function for the type MockRepository
func (_mock *MockRepository) IncrementOutboundMessages(ctx context.Context, channelID string, subtopic string) error {
	ret := _mock.Called(ctx, channelID, subtopic)

	if len(ret) == 0 {
		panic("no return value specified for IncrementOutboundMessages")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, channelID, subtopic)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_IncrementOutboundMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementOutboundMessages'
type MockRepository_IncrementOutboundMessages_Call struct {
	*mock.Call
}

// IncrementOutboundMessages is a helper method to define mock.On call
//   - ctx
//   - channelID
//   - subtopic
func (_e *MockRepository_Expecter) IncrementOutboundMessages(ctx interface{}, channelID interface{}, subtopic interface{}) *MockRepository_IncrementOutboundMessages_Call {
	return &MockRepository_IncrementOutboundMessages_Call{Call: _e.mock.On("IncrementOutboundMessages", ctx, channelID, subtopic)}
}

func (_c *MockRepository_IncrementOutboundMessages_Call) Run(run func(ctx context.Context, channelID string, subtopic string)) *MockRepository_IncrementOutboundMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRepository_IncrementOutboundMessages_Call) Return(err error) *MockRepository_IncrementOutboundMessages_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_IncrementOutboundMessages_Call) RunAndReturn(run func(ctx context.Context, channelID string, subtopic string) error) *MockRepository_IncrementOutboundMessages_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveSubscription provides a mock function for the type MockRepository
func (_mock *MockRepository) RemoveSubscription(ctx context.Context, subscriberID string) error {
	ret := _mock.Called(ctx, subscriberID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveSubscription")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, subscriberID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_RemoveSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveSubscription'
type MockRepository_RemoveSubscription_Call struct {
	*mock.Call
}

// RemoveSubscription is a helper method to define mock.On call
//   - ctx
//   - subscriberID
func (_e *MockRepository_Expecter) RemoveSubscription(ctx interface{}, subscriberID interface{}) *MockRepository_RemoveSubscription_Call {
	return &MockRepository_RemoveSubscription_Call{Call: _e.mock.On("RemoveSubscription", ctx, subscriberID)}
}

func (_c *MockRepository_RemoveSubscription_Call) Run(run func(ctx context.Context, subscriberID string)) *MockRepository_RemoveSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_RemoveSubscription_Call) Return(err error) *MockRepository_RemoveSubscription_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_RemoveSubscription_Call) RunAndReturn(run func(ctx context.Context, subscriberID string) error) *MockRepository_RemoveSubscription_Call {
	_c.Call.Return(run)
	return _c
}

// RetrieveAll provides a mock function for the type MockRepository
func (_mock *MockRepository) RetrieveAll(ctx context.Context, page journal.Page) (journal.JournalsPage, error) {
	ret := _mock.Called(ctx, page)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveAll")
	}

	var r0 journal.JournalsPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, journal.Page) (journal.JournalsPage, error)); ok {
		return returnFunc(ctx, page)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, journal.Page) journal.JournalsPage); ok {
		r0 = returnFunc(ctx, page)
	} else {
		r0 = ret.Get(0).(journal.JournalsPage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, journal.Page) error); ok {
		r1 = returnFunc(ctx, page)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_RetrieveAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveAll'
type MockRepository_RetrieveAll_Call struct {
	*mock.Call
}

// RetrieveAll is a helper method to define mock.On call
//   - ctx
//   - page
func (_e *MockRepository_Expecter) RetrieveAll(ctx interface{}, page interface{}) *MockRepository_RetrieveAll_Call {
	return &MockRepository_RetrieveAll_Call{Call: _e.mock.On("RetrieveAll", ctx, page)}
}

func (_c *MockRepository_RetrieveAll_Call) Run(run func(ctx context.Context, page journal.Page)) *MockRepository_RetrieveAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(journal.Page))
	})
	return _c
}

func (_c *MockRepository_RetrieveAll_Call) Return(journalsPage journal.JournalsPage, err error) *MockRepository_RetrieveAll_Call {
	_c.Call.Return(journalsPage, err)
	return _c
}

func (_c *MockRepository_RetrieveAll_Call) RunAndReturn(run func(ctx context.Context, page journal.Page) (journal.JournalsPage, error)) *MockRepository_RetrieveAll_Call {
	_c.Call.Return(run)
	return _c
}

// RetrieveClientTelemetry provides a mock function for the type MockRepository
func (_mock *MockRepository) RetrieveClientTelemetry(ctx context.Context, clientID string, domainID string) (journal.ClientTelemetry, error) {
	ret := _mock.Called(ctx, clientID, domainID)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveClientTelemetry")
	}

	var r0 journal.ClientTelemetry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (journal.ClientTelemetry, error)); ok {
		return returnFunc(ctx, clientID, domainID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) journal.ClientTelemetry); ok {
		r0 = returnFunc(ctx, clientID, domainID)
	} else {
		r0 = ret.Get(0).(journal.ClientTelemetry)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, clientID, domainID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_RetrieveClientTelemetry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveClientTelemetry'
type MockRepository_RetrieveClientTelemetry_Call struct {
	*mock.Call
}

// RetrieveClientTelemetry is a helper method to define mock.On call
//   - ctx
//   - clientID
//   - domainID
func (_e *MockRepository_Expecter) RetrieveClientTelemetry(ctx interface{}, clientID interface{}, domainID interface{}) *MockRepository_RetrieveClientTelemetry_Call {
	return &MockRepository_RetrieveClientTelemetry_Call{Call: _e.mock.On("RetrieveClientTelemetry", ctx, clientID, domainID)}
}

func (_c *MockRepository_RetrieveClientTelemetry_Call) Run(run func(ctx context.Context, clientID string, domainID string)) *MockRepository_RetrieveClientTelemetry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRepository_RetrieveClientTelemetry_Call) Return(clientTelemetry journal.ClientTelemetry, err error) *MockRepository_RetrieveClientTelemetry_Call {
	_c.Call.Return(clientTelemetry, err)
	return _c
}

func (_c *MockRepository_RetrieveClientTelemetry_Call) RunAndReturn(run func(ctx context.Context, clientID string, domainID string) (journal.ClientTelemetry, error)) *MockRepository_RetrieveClientTelemetry_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockRepository
func (_mock *MockRepository) Save(ctx context.Context, journal1 journal.Journal) error {
	ret := _mock.Called(ctx, journal1)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, journal.Journal) error); ok {
		r0 = returnFunc(ctx, journal1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx
//   - journal1
func (_e *MockRepository_Expecter) Save(ctx interface{}, journal1 interface{}) *MockRepository_Save_Call {
	return &MockRepository_Save_Call{Call: _e.mock.On("Save", ctx, journal1)}
}

func (_c *MockRepository_Save_Call) Run(run func(ctx context.Context, journal1 journal.Journal)) *MockRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(journal.Journal))
	})
	return _c
}

func (_c *MockRepository_Save_Call) Return(err error) *MockRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Save_Call) RunAndReturn(run func(ctx context.Context, journal1 journal.Journal) error) *MockRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// SaveClientTelemetry provides a mock function for the type MockRepository
func (_mock *MockRepository) SaveClientTelemetry(ctx context.Context, ct journal.ClientTelemetry) error {
	ret := _mock.Called(ctx, ct)

	if len(ret) == 0 {
		panic("no return value specified for SaveClientTelemetry")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, journal.ClientTelemetry) error); ok {
		r0 = returnFunc(ctx, ct)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_SaveClientTelemetry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveClientTelemetry'
type MockRepository_SaveClientTelemetry_Call struct {
	*mock.Call
}

// SaveClientTelemetry is a helper method to define mock.On call
//   - ctx
//   - ct
func (_e *MockRepository_Expecter) SaveClientTelemetry(ctx interface{}, ct interface{}) *MockRepository_SaveClientTelemetry_Call {
	return &MockRepository_SaveClientTelemetry_Call{Call: _e.mock.On("SaveClientTelemetry", ctx, ct)}
}

func (_c *MockRepository_SaveClientTelemetry_Call) Run(run func(ctx context.Context, ct journal.ClientTelemetry)) *MockRepository_SaveClientTelemetry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(journal.ClientTelemetry))
	})
	return _c
}

func (_c *MockRepository_SaveClientTelemetry_Call) Return(err error) *MockRepository_SaveClientTelemetry_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_SaveClientTelemetry_Call) RunAndReturn(run func(ctx context.Context, ct journal.ClientTelemetry) error) *MockRepository_SaveClientTelemetry_Call {
	_c.Call.Return(run)
	return _c
}
