// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify
// Copyright (c) Abstract Machines

// SPDX-License-Identifier: Apache-2.0

package mocks

import (
	"context"

	"github.com/absmach/supermq/pkg/policies"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEvaluator creates a new instance of MockEvaluator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEvaluator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEvaluator {
	mock := &MockEvaluator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEvaluator is an autogenerated mock type for the Evaluator type
type MockEvaluator struct {
	mock.Mock
}

type MockEvaluator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEvaluator) EXPECT() *MockEvaluator_Expecter {
	return &MockEvaluator_Expecter{mock: &_m.Mock}
}

// CheckPolicy provides a mock function for the type MockEvaluator
func (_mock *MockEvaluator) CheckPolicy(ctx context.Context, pr policies.Policy) error {
	ret := _mock.Called(ctx, pr)

	if len(ret) == 0 {
		panic("no return value specified for CheckPolicy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, policies.Policy) error); ok {
		r0 = returnFunc(ctx, pr)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEvaluator_CheckPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckPolicy'
type MockEvaluator_CheckPolicy_Call struct {
	*mock.Call
}

// CheckPolicy is a helper method to define mock.On call
//   - ctx
//   - pr
func (_e *MockEvaluator_Expecter) CheckPolicy(ctx interface{}, pr interface{}) *MockEvaluator_CheckPolicy_Call {
	return &MockEvaluator_CheckPolicy_Call{Call: _e.mock.On("CheckPolicy", ctx, pr)}
}

func (_c *MockEvaluator_CheckPolicy_Call) Run(run func(ctx context.Context, pr policies.Policy)) *MockEvaluator_CheckPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(policies.Policy))
	})
	return _c
}

func (_c *MockEvaluator_CheckPolicy_Call) Return(err error) *MockEvaluator_CheckPolicy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEvaluator_CheckPolicy_Call) RunAndReturn(run func(ctx context.Context, pr policies.Policy) error) *MockEvaluator_CheckPolicy_Call {
	_c.Call.Return(run)
	return _c
}
