// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify
// Copyright (c) Abstract Machines

// SPDX-License-Identifier: Apache-2.0

package mocks

import (
	"context"

	"github.com/absmach/supermq/pkg/policies"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// AddPolicies provides a mock function for the type MockService
func (_mock *MockService) AddPolicies(ctx context.Context, prs []policies.Policy) error {
	ret := _mock.Called(ctx, prs)

	if len(ret) == 0 {
		panic("no return value specified for AddPolicies")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []policies.Policy) error); ok {
		r0 = returnFunc(ctx, prs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_AddPolicies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPolicies'
type MockService_AddPolicies_Call struct {
	*mock.Call
}

// AddPolicies is a helper method to define mock.On call
//   - ctx
//   - prs
func (_e *MockService_Expecter) AddPolicies(ctx interface{}, prs interface{}) *MockService_AddPolicies_Call {
	return &MockService_AddPolicies_Call{Call: _e.mock.On("AddPolicies", ctx, prs)}
}

func (_c *MockService_AddPolicies_Call) Run(run func(ctx context.Context, prs []policies.Policy)) *MockService_AddPolicies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]policies.Policy))
	})
	return _c
}

func (_c *MockService_AddPolicies_Call) Return(err error) *MockService_AddPolicies_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_AddPolicies_Call) RunAndReturn(run func(ctx context.Context, prs []policies.Policy) error) *MockService_AddPolicies_Call {
	_c.Call.Return(run)
	return _c
}

// AddPolicy provides a mock function for the type MockService
func (_mock *MockService) AddPolicy(ctx context.Context, pr policies.Policy) error {
	ret := _mock.Called(ctx, pr)

	if len(ret) == 0 {
		panic("no return value specified for AddPolicy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, policies.Policy) error); ok {
		r0 = returnFunc(ctx, pr)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_AddPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPolicy'
type MockService_AddPolicy_Call struct {
	*mock.Call
}

// AddPolicy is a helper method to define mock.On call
//   - ctx
//   - pr
func (_e *MockService_Expecter) AddPolicy(ctx interface{}, pr interface{}) *MockService_AddPolicy_Call {
	return &MockService_AddPolicy_Call{Call: _e.mock.On("AddPolicy", ctx, pr)}
}

func (_c *MockService_AddPolicy_Call) Run(run func(ctx context.Context, pr policies.Policy)) *MockService_AddPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(policies.Policy))
	})
	return _c
}

func (_c *MockService_AddPolicy_Call) Return(err error) *MockService_AddPolicy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_AddPolicy_Call) RunAndReturn(run func(ctx context.Context, pr policies.Policy) error) *MockService_AddPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// CountObjects provides a mock function for the type MockService
func (_mock *MockService) CountObjects(ctx context.Context, pr policies.Policy) (uint64, error) {
	ret := _mock.Called(ctx, pr)

	if len(ret) == 0 {
		panic("no return value specified for CountObjects")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, policies.Policy) (uint64, error)); ok {
		return returnFunc(ctx, pr)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, policies.Policy) uint64); ok {
		r0 = returnFunc(ctx, pr)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, policies.Policy) error); ok {
		r1 = returnFunc(ctx, pr)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_CountObjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountObjects'
type MockService_CountObjects_Call struct {
	*mock.Call
}

// CountObjects is a helper method to define mock.On call
//   - ctx
//   - pr
func (_e *MockService_Expecter) CountObjects(ctx interface{}, pr interface{}) *MockService_CountObjects_Call {
	return &MockService_CountObjects_Call{Call: _e.mock.On("CountObjects", ctx, pr)}
}

func (_c *MockService_CountObjects_Call) Run(run func(ctx context.Context, pr policies.Policy)) *MockService_CountObjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(policies.Policy))
	})
	return _c
}

func (_c *MockService_CountObjects_Call) Return(v uint64, err error) *MockService_CountObjects_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockService_CountObjects_Call) RunAndReturn(run func(ctx context.Context, pr policies.Policy) (uint64, error)) *MockService_CountObjects_Call {
	_c.Call.Return(run)
	return _c
}

// CountSubjects provides a mock function for the type MockService
func (_mock *MockService) CountSubjects(ctx context.Context, pr policies.Policy) (uint64, error) {
	ret := _mock.Called(ctx, pr)

	if len(ret) == 0 {
		panic("no return value specified for CountSubjects")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, policies.Policy) (uint64, error)); ok {
		return returnFunc(ctx, pr)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, policies.Policy) uint64); ok {
		r0 = returnFunc(ctx, pr)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, policies.Policy) error); ok {
		r1 = returnFunc(ctx, pr)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_CountSubjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountSubjects'
type MockService_CountSubjects_Call struct {
	*mock.Call
}

// CountSubjects is a helper method to define mock.On call
//   - ctx
//   - pr
func (_e *MockService_Expecter) CountSubjects(ctx interface{}, pr interface{}) *MockService_CountSubjects_Call {
	return &MockService_CountSubjects_Call{Call: _e.mock.On("CountSubjects", ctx, pr)}
}

func (_c *MockService_CountSubjects_Call) Run(run func(ctx context.Context, pr policies.Policy)) *MockService_CountSubjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(policies.Policy))
	})
	return _c
}

func (_c *MockService_CountSubjects_Call) Return(v uint64, err error) *MockService_CountSubjects_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockService_CountSubjects_Call) RunAndReturn(run func(ctx context.Context, pr policies.Policy) (uint64, error)) *MockService_CountSubjects_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePolicies provides a mock function for the type MockService
func (_mock *MockService) DeletePolicies(ctx context.Context, prs []policies.Policy) error {
	ret := _mock.Called(ctx, prs)

	if len(ret) == 0 {
		panic("no return value specified for DeletePolicies")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []policies.Policy) error); ok {
		r0 = returnFunc(ctx, prs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeletePolicies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePolicies'
type MockService_DeletePolicies_Call struct {
	*mock.Call
}

// DeletePolicies is a helper method to define mock.On call
//   - ctx
//   - prs
func (_e *MockService_Expecter) DeletePolicies(ctx interface{}, prs interface{}) *MockService_DeletePolicies_Call {
	return &MockService_DeletePolicies_Call{Call: _e.mock.On("DeletePolicies", ctx, prs)}
}

func (_c *MockService_DeletePolicies_Call) Run(run func(ctx context.Context, prs []policies.Policy)) *MockService_DeletePolicies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]policies.Policy))
	})
	return _c
}

func (_c *MockService_DeletePolicies_Call) Return(err error) *MockService_DeletePolicies_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeletePolicies_Call) RunAndReturn(run func(ctx context.Context, prs []policies.Policy) error) *MockService_DeletePolicies_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePolicyFilter provides a mock function for the type MockService
func (_mock *MockService) DeletePolicyFilter(ctx context.Context, pr policies.Policy) error {
	ret := _mock.Called(ctx, pr)

	if len(ret) == 0 {
		panic("no return value specified for DeletePolicyFilter")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, policies.Policy) error); ok {
		r0 = returnFunc(ctx, pr)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeletePolicyFilter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePolicyFilter'
type MockService_DeletePolicyFilter_Call struct {
	*mock.Call
}

// DeletePolicyFilter is a helper method to define mock.On call
//   - ctx
//   - pr
func (_e *MockService_Expecter) DeletePolicyFilter(ctx interface{}, pr interface{}) *MockService_DeletePolicyFilter_Call {
	return &MockService_DeletePolicyFilter_Call{Call: _e.mock.On("DeletePolicyFilter", ctx, pr)}
}

func (_c *MockService_DeletePolicyFilter_Call) Run(run func(ctx context.Context, pr policies.Policy)) *MockService_DeletePolicyFilter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(policies.Policy))
	})
	return _c
}

func (_c *MockService_DeletePolicyFilter_Call) Return(err error) *MockService_DeletePolicyFilter_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeletePolicyFilter_Call) RunAndReturn(run func(ctx context.Context, pr policies.Policy) error) *MockService_DeletePolicyFilter_Call {
	_c.Call.Return(run)
	return _c
}

// ListAllObjects provides a mock function for the type MockService
func (_mock *MockService) ListAllObjects(ctx context.Context, pr policies.Policy) (policies.PolicyPage, error) {
	ret := _mock.Called(ctx, pr)

	if len(ret) == 0 {
		panic("no return value specified for ListAllObjects")
	}

	var r0 policies.PolicyPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, policies.Policy) (policies.PolicyPage, error)); ok {
		return returnFunc(ctx, pr)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, policies.Policy) policies.PolicyPage); ok {
		r0 = returnFunc(ctx, pr)
	} else {
		r0 = ret.Get(0).(policies.PolicyPage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, policies.Policy) error); ok {
		r1 = returnFunc(ctx, pr)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListAllObjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAllObjects'
type MockService_ListAllObjects_Call struct {
	*mock.Call
}

// ListAllObjects is a helper method to define mock.On call
//   - ctx
//   - pr
func (_e *MockService_Expecter) ListAllObjects(ctx interface{}, pr interface{}) *MockService_ListAllObjects_Call {
	return &MockService_ListAllObjects_Call{Call: _e.mock.On("ListAllObjects", ctx, pr)}
}

func (_c *MockService_ListAllObjects_Call) Run(run func(ctx context.Context, pr policies.Policy)) *MockService_ListAllObjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(policies.Policy))
	})
	return _c
}

func (_c *MockService_ListAllObjects_Call) Return(policyPage policies.PolicyPage, err error) *MockService_ListAllObjects_Call {
	_c.Call.Return(policyPage, err)
	return _c
}

func (_c *MockService_ListAllObjects_Call) RunAndReturn(run func(ctx context.Context, pr policies.Policy) (policies.PolicyPage, error)) *MockService_ListAllObjects_Call {
	_c.Call.Return(run)
	return _c
}

// ListAllSubjects provides a mock function for the type MockService
func (_mock *MockService) ListAllSubjects(ctx context.Context, pr policies.Policy) (policies.PolicyPage, error) {
	ret := _mock.Called(ctx, pr)

	if len(ret) == 0 {
		panic("no return value specified for ListAllSubjects")
	}

	var r0 policies.PolicyPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, policies.Policy) (policies.PolicyPage, error)); ok {
		return returnFunc(ctx, pr)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, policies.Policy) policies.PolicyPage); ok {
		r0 = returnFunc(ctx, pr)
	} else {
		r0 = ret.Get(0).(policies.PolicyPage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, policies.Policy) error); ok {
		r1 = returnFunc(ctx, pr)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListAllSubjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAllSubjects'
type MockService_ListAllSubjects_Call struct {
	*mock.Call
}

// ListAllSubjects is a helper method to define mock.On call
//   - ctx
//   - pr
func (_e *MockService_Expecter) ListAllSubjects(ctx interface{}, pr interface{}) *MockService_ListAllSubjects_Call {
	return &MockService_ListAllSubjects_Call{Call: _e.mock.On("ListAllSubjects", ctx, pr)}
}

func (_c *MockService_ListAllSubjects_Call) Run(run func(ctx context.Context, pr policies.Policy)) *MockService_ListAllSubjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(policies.Policy))
	})
	return _c
}

func (_c *MockService_ListAllSubjects_Call) Return(policyPage policies.PolicyPage, err error) *MockService_ListAllSubjects_Call {
	_c.Call.Return(policyPage, err)
	return _c
}

func (_c *MockService_ListAllSubjects_Call) RunAndReturn(run func(ctx context.Context, pr policies.Policy) (policies.PolicyPage, error)) *MockService_ListAllSubjects_Call {
	_c.Call.Return(run)
	return _c
}

// ListObjects provides a mock function for the type MockService
func (_mock *MockService) ListObjects(ctx context.Context, pr policies.Policy, nextPageToken string, limit uint64) (policies.PolicyPage, error) {
	ret := _mock.Called(ctx, pr, nextPageToken, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListObjects")
	}

	var r0 policies.PolicyPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, policies.Policy, string, uint64) (policies.PolicyPage, error)); ok {
		return returnFunc(ctx, pr, nextPageToken, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, policies.Policy, string, uint64) policies.PolicyPage); ok {
		r0 = returnFunc(ctx, pr, nextPageToken, limit)
	} else {
		r0 = ret.Get(0).(policies.PolicyPage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, policies.Policy, string, uint64) error); ok {
		r1 = returnFunc(ctx, pr, nextPageToken, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListObjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListObjects'
type MockService_ListObjects_Call struct {
	*mock.Call
}

// ListObjects is a helper method to define mock.On call
//   - ctx
//   - pr
//   - nextPageToken
//   - limit
func (_e *MockService_Expecter) ListObjects(ctx interface{}, pr interface{}, nextPageToken interface{}, limit interface{}) *MockService_ListObjects_Call {
	return &MockService_ListObjects_Call{Call: _e.mock.On("ListObjects", ctx, pr, nextPageToken, limit)}
}

func (_c *MockService_ListObjects_Call) Run(run func(ctx context.Context, pr policies.Policy, nextPageToken string, limit uint64)) *MockService_ListObjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(policies.Policy), args[2].(string), args[3].(uint64))
	})
	return _c
}

func (_c *MockService_ListObjects_Call) Return(policyPage policies.PolicyPage, err error) *MockService_ListObjects_Call {
	_c.Call.Return(policyPage, err)
	return _c
}

func (_c *MockService_ListObjects_Call) RunAndReturn(run func(ctx context.Context, pr policies.Policy, nextPageToken string, limit uint64) (policies.PolicyPage, error)) *MockService_ListObjects_Call {
	_c.Call.Return(run)
	return _c
}

// ListPermissions provides a mock function for the type MockService
func (_mock *MockService) ListPermissions(ctx context.Context, pr policies.Policy, permissionsFilter []string) (policies.Permissions, error) {
	ret := _mock.Called(ctx, pr, permissionsFilter)

	if len(ret) == 0 {
		panic("no return value specified for ListPermissions")
	}

	var r0 policies.Permissions
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, policies.Policy, []string) (policies.Permissions, error)); ok {
		return returnFunc(ctx, pr, permissionsFilter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, policies.Policy, []string) policies.Permissions); ok {
		r0 = returnFunc(ctx, pr, permissionsFilter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(policies.Permissions)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, policies.Policy, []string) error); ok {
		r1 = returnFunc(ctx, pr, permissionsFilter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPermissions'
type MockService_ListPermissions_Call struct {
	*mock.Call
}

// ListPermissions is a helper method to define mock.On call
//   - ctx
//   - pr
//   - permissionsFilter
func (_e *MockService_Expecter) ListPermissions(ctx interface{}, pr interface{}, permissionsFilter interface{}) *MockService_ListPermissions_Call {
	return &MockService_ListPermissions_Call{Call: _e.mock.On("ListPermissions", ctx, pr, permissionsFilter)}
}

func (_c *MockService_ListPermissions_Call) Run(run func(ctx context.Context, pr policies.Policy, permissionsFilter []string)) *MockService_ListPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(policies.Policy), args[2].([]string))
	})
	return _c
}

func (_c *MockService_ListPermissions_Call) Return(permissions policies.Permissions, err error) *MockService_ListPermissions_Call {
	_c.Call.Return(permissions, err)
	return _c
}

func (_c *MockService_ListPermissions_Call) RunAndReturn(run func(ctx context.Context, pr policies.Policy, permissionsFilter []string) (policies.Permissions, error)) *MockService_ListPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// ListSubjects provides a mock function for the type MockService
func (_mock *MockService) ListSubjects(ctx context.Context, pr policies.Policy, nextPageToken string, limit uint64) (policies.PolicyPage, error) {
	ret := _mock.Called(ctx, pr, nextPageToken, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListSubjects")
	}

	var r0 policies.PolicyPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, policies.Policy, string, uint64) (policies.PolicyPage, error)); ok {
		return returnFunc(ctx, pr, nextPageToken, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, policies.Policy, string, uint64) policies.PolicyPage); ok {
		r0 = returnFunc(ctx, pr, nextPageToken, limit)
	} else {
		r0 = ret.Get(0).(policies.PolicyPage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, policies.Policy, string, uint64) error); ok {
		r1 = returnFunc(ctx, pr, nextPageToken, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListSubjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSubjects'
type MockService_ListSubjects_Call struct {
	*mock.Call
}

// ListSubjects is a helper method to define mock.On call
//   - ctx
//   - pr
//   - nextPageToken
//   - limit
func (_e *MockService_Expecter) ListSubjects(ctx interface{}, pr interface{}, nextPageToken interface{}, limit interface{}) *MockService_ListSubjects_Call {
	return &MockService_ListSubjects_Call{Call: _e.mock.On("ListSubjects", ctx, pr, nextPageToken, limit)}
}

func (_c *MockService_ListSubjects_Call) Run(run func(ctx context.Context, pr policies.Policy, nextPageToken string, limit uint64)) *MockService_ListSubjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(policies.Policy), args[2].(string), args[3].(uint64))
	})
	return _c
}

func (_c *MockService_ListSubjects_Call) Return(policyPage policies.PolicyPage, err error) *MockService_ListSubjects_Call {
	_c.Call.Return(policyPage, err)
	return _c
}

func (_c *MockService_ListSubjects_Call) RunAndReturn(run func(ctx context.Context, pr policies.Policy, nextPageToken string, limit uint64) (policies.PolicyPage, error)) *MockService_ListSubjects_Call {
	_c.Call.Return(run)
	return _c
}
